cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from shop.forms import CartAddProduct


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    kwargs = {'prod_id': product.id}
    form = CartAddProduct(request.POST, **kwargs)
    if form.is_valid():
        print("added product********")
        cd = form.cleaned_data
        print(str(cd['color']))
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'],
                 color=str(cd['color'],))
        cart.save()
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            print(item)
            kwargs = {'prod_id': item['product'].id}
            item['update_quantity_form'] = CartAddProduct(
                              initial={'quantity': item['quantity'],
                              'update': True,}, **kwargs)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  tu carrito de compra
{% endblock %}

{% block content %}
  <h1>Tu carrito de compra</h1>
<div class="table-responsive">
  <table class="cart " id="theTable">
    <thead>
      <tr>
        <th>Imagen</th>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Remover</th>
        <th>Precio Unidad</th>
        <th class="headcol">Precio</th>
      </tr>
    </thead>
    <tbody>
      {% if not cart %}
      <p>Vacio</p>
      {% endif %}
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img  src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}  <strong>{{item.color}}</strong></td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" class="btn btn-primary btn-sm" value="Cambiar">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url "cart:cart_remove" product.id %}">Remover</a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
</div>
<div class="m-3">
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="btn btn-secondary p-1">Continuar Comprando</a>

    <a href="{% url 'orders:order_create' %}" class="btn btn-primary p-1">
    Siguiente
    </a>
  </p>
</div>
{% endblock %}