cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Color(models.Model):
    product = models.ManyToManyField(Product, related_name='colors')
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from .models import Color

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProduct(forms.Form):

    def __init__(self, *args, **kwargs):
        prod_id = kwargs.pop('prod_id')
        super().__init__(*args, **kwargs)
        self.fields['color'] = forms.ModelChoiceField(Color.objects.filter(product__id=prod_id),
                                                      empty_label='Seleccione color')

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Cantidad')
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from .forms import CartAddProduct

# Create your views here.

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    kwargs = {'prod_id': product.id}
    form = CartAddProduct(**kwargs)
    return render(request, 'shop/product/detail.html', {'form': form, 'product':product})

shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Tapabocas GO{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1/css/bootstrap.min.css' %}">
    <!--fontawesome-->
    <link href="{% static 'fontawesome-free-5.11.2-web/css/all.css' %}" rel='stylesheet'/>
    <!--fontawesome-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div id="header">
        <a href="/" class="logo"><strong>Tapabocas GO</strong> <img src="{% get_media_prefix %}logo-go.png" height="30"> </a>

        <img class="float-right" src="{% get_media_prefix %}logo_mt.jpeg" height="55">
    </div>
    <div id="subheader">
        <div class="cart col-6 ">
            {% with total_items=cart|length %}
            <div class="float-right">
                {% if cart|length > 0 %}
                Tu carrito<i class="fas fa-shopping-cart"></i>:
                    <a href="{% url "cart:cart_detail" %}">
                    {{ total_items }} producto{{ total_items|pluralize }},
                     ${{ cart.get_total_price }}
                    </a>
                    {% else %}
                Tu carrito esta vacio. <i class="fas fa-shopping-cart"></i>
                {% endif %}
            </div>
            {% endwith %}
        </div>
        <div class="col-6">
        <span>Ventas solo en la ciudad de <strong>Fusagasugá</strong></span>
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="footer">
        <span></span><img class="float-right" src="{% get_media_prefix %}lafayette_nbg.png" height="0"></span>
        <span>El<strong> PAGO </strong>se realiza contra-entrega o por <strong>NEQUI</strong>. Te lo llevemos a tu casa
        o puedes recogerlo en nuestra fabrica.<br> <strong>Dirección:</strong>Transversal 12 # 16B - 32. Cerca Clinica Belen
        </span>
    </div>
    <!--ajax.js-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!--ajax.js-->
    <!--sweet alert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!--sweet alert-->
    <script src="{% static 'bootstrap-4.4.1/js/bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>